### ISSUE TITLE
Returning Error on Setting JSON

### ISSUE THREAD

**Issue by dinilv** [KromDaniel/rejonson#1]
Trying to save a json using  reJonson. getting Error

`log.Println("Map",saveJson)
	//convert to unsafe text
	jsonString:=bytes.NewBuffer(jsonBytes).String()
	_,err=reJsonClient.JsonSet(key,".",jsonString).Result()
	if err!=nil{
		log.Println("error",err)
		return false
	}`

Error Log:

` error ERR unknown command `JSON.SET`, with args beginning with: `test1`, `.`, `{"check":"salary","future":"uncertain","satisfied":"work"}`, 

`

**Comment by KromDaniel** [comment]
Hey
What is the type of saveJson? can you show the value you get from jsonString?

Just to make sure, did you install the rejson module on your redis?

**Comment by dinilv** [comment]
Not a BUG
Closing issue. Thanks for quick reply.
