### ISSUE TITLE
ERR Client sent AUTH, but no password is set

### ISSUE THREAD

**Issue by Tyxiang** [KromDaniel/rejonson#2]
I am connecting to a redis service that requires a password: 
```go
    goRedisClient := redis.NewClient(&redis.Options{
        Addr:     "abc.com:8000",
        Password: "xxxxxxxxx",
        DB:       0,
    })
```
When I call `client.JsonGet()` method, I get an error message：

`ERR Client sent AUTH, but no password is set` 

Looks like something went wrong about the password.

**Comment by KromDaniel** [comment]
This is not client issue, the error means that you sent password to Redis but the Redis doesn't require password at all. If you try empty password you shouldn't get this error

**Comment by Tyxiang** [comment]
> This is not client issue, the error means that you sent password to Redis but the Redis doesn't require password at all. If you try empty password you shouldn't get this error

This should be a bug of "github.com/go-redis/redis/".  I have reported [here](https://github.com/go-redis/redis/issues/1376).
