### ISSUE TITLE
go-redis/v8 and UniversalClient support

### ISSUE THREAD

**Issue by pffs** [KromDaniel/rejonson#3]
`ExtendClient` currently on works with the unversioned branch of go-redis (which is currently stuck at v6 for me). The go-redis project currently recommends using their v8 client which gives me a type error.

One nice thing added into the v8 client is the `UniversalClient` (https://pkg.go.dev/github.com/go-redis/redis/v8#UniversalClient) which will automatically create a regular redis, sentinel, or cluster client based on opts passed.

I'm not sure how difficult these would be to support, but if you have a general outline of what needs added I can try adding in a PR for them if it's not something you plan or have time to add.

**Comment by KromDaniel** [comment]
Fixed, rejonson supports now multiple go-redis clients
